# --------------------- Install ---------------------
install:
    pip install -r requirements.txt
    
# --------------------- Train ---------------------
train:
    make train-bot
    
train-bot:
    python train.py 

# --------------------- Test ---------------------
test:
    make test-bot
    
test-bot:
    python test.py
 
